name: reusable wf
on: 
  workflow_call:
     inputs:
       name:
         description: 'Name to greet'
         required: true
         default: 'World'
jobs:
   greeting:
     runs-on: ubuntu-latest
     steps:
        - name: greeting
          run: echo "Hello ${{ inputs.name }} from reusable"
# Hello